### ISSUE TITLE
RtcLocalView.SurfaceView not working on Release APK

### ISSUE THREAD

**Issue by kennguyen1506** [AgoraIO-Community/react-native-agora#249]
Hi, I have an issues with Agora functions not working when I build a release APK for Android.

Android ver: 10
ReactNative ver: 0.62.2
react-native-agora: 3.0.1-rc.3

I already upgraded everything to the latest versions and made sure that all permissions are added in my AndroidManifest.xml.

Also have permission checks fired when app is opened.

RtcLocalView and RtcRemoteView are not displaying, my users are not able to Join agora channel.
These seems to work on debug mode.

Have anyone experience this issue? 
I'm not sure what codes you would like to look att, so if you guys want me to provide anything, let me know.

Thank you for the help!

**Comment by LichKing-2234** [comment]
can you provide our SDK log？

**Comment by kennguyen1506** [comment]
would you mind give me a quick instruction to get the SDK log? 
I'm not sure if its the catlog from android studio or are you preferring to something else.

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ab25d55c7f95903ff09280e308a977c08

**Comment by kennguyen1506** [comment]
[agorasdk_3.0.1.1.log](https://github.com/AgoraIO-Community/react-native-agora/files/5015601/agorasdk_3.0.1.1.log)

I have attached the most recent log from a debug build.
I was not able to create a build log on a release APK.

The specific functions I tried to run were Rtc.create() and Rtc.LocalView/Rtc.RemoteView. These run fine on iOS and Debug, however.

I wonder if the cause is because of code obfuscation?

If that is the case, here is my build configuration:

android {
... buildTypes {
     ... {
          ... release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
         }
      }
   }
}

I made sure to include (-keep class io.agora.**{*;}) in my proguard-rules.pro. Please let me know if there should be any additional config.

Also, Is it necessary to have a Dynamic Token server setup for users to join the channel in the production environment?

**Comment by kennguyen1506** [comment]
@LichKing-2234 Hi there,

I adjusted my build config as follow: `android {
... buildTypes {
... release {
           minifyEnabled enableProguardInReleaseBuilds
            shrinkResources false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
}
}
}`

And set android.useR8=false to disable R8. After that, my release APK is working in lower android version (LGv20 android 7). But it does not work yet on Samsung phones with android 10. Could it be because of conflicting architecture?

**Comment by LichKing-2234** [comment]
fixed in 3.0.1-rc.4

**Comment by kennguyen1506** [comment]
@LichKing-2234 hi, thank you for the update.

But this update does not seem to fix my problem. The camera still does not work on android 9 and android 10 devices.
Could you re-upload a working example? Thank you!
